const wittyMotivations = [
  "You look like you have more craters than the moon",
  "It would help if you were the poster child of a condom company",
  "You’re about as useful as the white crayon",
  "Did you use a mud puddle as a mirror this morning?",
  "Were you carrying an umbrella when God was giving out beauty?",
  "Explaining to you is like teaching calculus to a lemur",
  "If you ran like your mouth, maybe you’d win a gold medal",
  "You’re as sharp as a marble",
  "There’s some shit on your clothes. Oh, nope. That’s just you",
  "You're about as helpful as a screen door on a submarine.",
  "If brains were dynamite, you wouldn’t have enough to blow your nose.",
  "You're the human version of a typo.",
  "I’ve seen parking lots with more depth than you.",
  "You must have been a great backup plan for someone’s bad decision.",
  "The wheel’s spinning, but the hamster’s long gone.",
  "You’re proof that evolution can go in reverse.",
  "If ignorance is bliss, you must be on cloud nine.",
  "Your brain cells must’ve filed for divorce.",
  "Coding with you feels like playing chess with a pigeon.",
  "You're about as useful as a chocolate teapot.",
  "If you were any more basic, you'd be a default setting.",
  "You're like a software update—nobody wants you, but we have to deal with you.",
  "You have the charisma of a damp rag.",
  "You're the reason God created the middle finger.",
  "If common sense were currency, you'd be bankrupt.",
  "You're like a broken pencil—pointless.",
  "If I wanted to hear from an asshole, I’d fart.",
  "You're the human equivalent of a participation trophy.",
  "You're about as useful as a chocolate teapot.",
  "If you were any more basic, you'd be a default setting.",
  "You're like a software update—nobody wants you, but we have to deal with you.",
  "You have the charisma of a damp rag.",
  "You're the reason God created the middle finger.",
  "If common sense were currency, you'd be bankrupt.",
  "You're like a broken pencil—pointless.",
  "If I wanted to hear from an asshole, I’d fart.",
  "You’re as bright as a black hole and twice as dense.",
  "You're the human equivalent of a participation trophy.",
  "You look like a before picture for a makeover show.",
  "If you were any more dense, you'd be a black hole.",
  "You're like a software bug—nobody wants you around.",
  "I’d explain it to you, but I left my English-to-Dingbat dictionary at home.",
  "You’re like a broken clock—right twice a day, and utterly useless the rest.",
  "If you were any more basic, you’d be a default setting on a toaster.",
  "You have the charm of a soggy cardboard box.",
  "You’re living proof that even evolution can take a vacation.",
  "You're the human version of a participation trophy—nice, but utterly pointless.",
  "You’re like a cloud—when you disappear, it's a beautiful day.",
  "If ignorance is bliss, you must be the happiest person alive.",
  "I’d call you a tool, but that implies you’re useful.",
  "You're the reason the gene pool needs a lifeguard.",
  "You’re about as welcome as a skunk at a garden party.",
  "If you were any more of a train wreck, you’d have your own reality show.",
  "Your face makes onions cry.",
  "You’re like a Wi-Fi signal in the mountains—weak and rarely connected.",
  "I’ve met houseplants with better conversation skills.",
  "You’re the reason they put directions on shampoo bottles.",
  "well, shit"
];

const codingMotivation = [
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
    "My code doesn’t always work, but when it does, I have no idea why.",
    "I put the 'pro' in 'procrastinate' when it comes to coding.",
    "If at first you don’t succeed, call it version 1.0.",
    "I have a special talent for turning coffee into code errors.",
    "I’m on the no-debugging diet. I just can’t stop eating bugs.",
    "My favorite programming language is procrastination.",
    "You know you're a bad coder when even your comments are out of date.",
    "I don't need a debugger; I just need a miracle.",
    "My code has more bugs than an entomologist's lab.",
    "I thought I was a decent coder until I realized I was just very good at Googling.",
    "My code doesn’t just crash; it takes the whole system down with it.",
    "If my code were a car, it would be in the shop more than on the road.",
    "I’m not saying I’m a bad coder, but I did once create a bug that had a fan club.",
    "I tried to make a list, but my code just kept crashing.",
    "My code and I have a love-hate relationship: I love to write it, and it hates to run.",
    "I could optimize my code, but then I’d have to figure out what it does first.",
    "I finally understand why my code is so bad: it's a reflection of my mental state.",
    "My coding skills are like a broken pencil—pointless.",
    "I’m not a complete idiot; some parts are missing.",
    "When it comes to coding, I'm an expert in undefined behavior.",
    "I’d comment my code if I could figure out what it does.",
    "I tried to write a program, but it ended up being a memoir of my failures.",
    "I’m not bad at coding; I’m just exceptionally good at finding new ways to fail.",
    "My code is like a fine wine—it gets better with age and some serious tweaking.",
    "I finally learned how to make my code work: by moving it to the trash.",
    "My code is so messy, it should come with a hazard warning.",
    "I’ve learned that every time I fix one bug, two more show up for the party.",
    "If my coding style were a book, it would be a horror novel.",
    "I’m like a software magician—now you see the bug, now you don’t.",
    "If bad code were an Olympic sport, I’d have a gold medal.",
    "My coding skills are like a flip-flop; they work half the time and are uncomfortable the rest.",
    "I once tried to write a function, but it turned into a tragedy.",
    "My code is like a bad joke—everyone groans, and no one laughs.",
    "When I debug, I’m just looking for ways to make it worse.",
    "I think my code is allergic to success; it always breaks out in errors.",
    "I could explain my code, but that would require a PhD in nonsense.",
    "My code and I are in a committed relationship; we both can't function without the other.",
    "I’m like a compiler that keeps throwing errors—it just can’t handle the truth.",
    "My favorite programming exercise is turning a simple task into a weekend project.",
    "I can write code, but I can’t write documentation. Guess which one’s more useful?",
    "I wrote a book on coding; it's titled 'How to Fail Gracefully.'",
    "My code is a reflection of my personality: chaotic, confusing, and occasionally functional.",
    "If coding were a language, I’d be fluent in gibberish.",
    "I don’t always test my code, but when I do, I prefer to do it in production.",
    "If there’s a way to make a simple task complex, I will find it.",
    "I’m not a bad coder; I just have a unique approach to problem-solving.",
    "My coding journey is like a roller coaster—full of ups and downs and a lot of screaming.",
    "I’m the reason they put ‘don’t try this at home’ on code samples.",
    "I’d say my code is like Swiss cheese—full of holes but somehow holds together.",
    "If coding was a crime, I’d be serving a life sentence."
];

exports.MOTIVATION_ARRAY = wittyMotivations;
exports.CODING_MOTIVATION_ARRAY = codingMotivation;
