const wittyMotivations = [
  "You look like you have more craters than the moon",
  "It would help if you were the poster child of a condom company",
  "You’re about as useful as the white crayon",
  "Did you use a mud puddle as a mirror this morning?",
  "Were you carrying an umbrella when God was giving out beauty?",
  "Explaining to you is like teaching calculus to a lemur",
  "If you ran like your mouth, maybe you’d win a gold medal",
  "You’re as sharp as a marble",
  "There’s some shit on your clothes. Oh, nope. That’s just you",
  "You're about as helpful as a screen door on a submarine.",
  "If brains were dynamite, you wouldn’t have enough to blow your nose.",
  "You're the human version of a typo.",
  "I’ve seen parking lots with more depth than you.",
  "You must have been a great backup plan for someone’s bad decision.",
  "The wheel’s spinning, but the hamster’s long gone.",
  "You’re proof that evolution can go in reverse.",
  "If ignorance is bliss, you must be on cloud nine.",
  "Your brain cells must’ve filed for divorce.",
  "Coding with you feels like playing chess with a pigeon.",
  "You're about as useful as a chocolate teapot.",
  "If you were any more basic, you'd be a default setting.",
  "You're like a software update—nobody wants you, but we have to deal with you.",
  "You have the charisma of a damp rag.",
  "You're the reason God created the middle finger.",
  "If common sense were currency, you'd be bankrupt.",
  "You're like a broken pencil—pointless.",
  "If I wanted to hear from an asshole, I’d fart.",
  "You're the human equivalent of a participation trophy.",
  "You're about as useful as a chocolate teapot.",
  "If you were any more basic, you'd be a default setting.",
  "You're like a software update—nobody wants you, but we have to deal with you.",
  "You have the charisma of a damp rag.",
  "You're the reason God created the middle finger.",
  "If common sense were currency, you'd be bankrupt.",
  "You're like a broken pencil—pointless.",
  "If I wanted to hear from an asshole, I’d fart.",
  "You’re as bright as a black hole and twice as dense.",
  "You're the human equivalent of a participation trophy.",
  "You look like a before picture for a makeover show.",
  "If you were any more dense, you'd be a black hole.",
  "You're like a software bug—nobody wants you around.",
  "I’d explain it to you, but I left my English-to-Dingbat dictionary at home.",
  "You’re like a broken clock—right twice a day, and utterly useless the rest.",
  "If you were any more basic, you’d be a default setting on a toaster.",
  "You have the charm of a soggy cardboard box.",
  "You’re living proof that even evolution can take a vacation.",
  "You're the human version of a participation trophy—nice, but utterly pointless.",
  "You’re like a cloud—when you disappear, it's a beautiful day.",
  "If ignorance is bliss, you must be the happiest person alive.",
  "I’d call you a tool, but that implies you’re useful.",
  "You're the reason the gene pool needs a lifeguard.",
  "You’re about as welcome as a skunk at a garden party.",
  "If you were any more of a train wreck, you’d have your own reality show.",
  "Your face makes onions cry.",
  "You’re like a Wi-Fi signal in the mountains—weak and rarely connected.",
  "I’ve met houseplants with better conversation skills.",
  "You’re the reason they put directions on shampoo bottles.",
  "well, shit"
];

exports.MOTIVATION_ARRAY = wittyMotivations;
